name: Docker Pushing

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t muhhassani/pyiron-precice:latest .
      - run: docker tag muhhassani/pyiron-precice:latest muhhassani/pyiron-precice:"$(date +%F)"
      - run: docker images
      - run: docker push muhhassani/pyiron-precice:latest
      - run: docker push muhhassani/pyiron-precice:"$(date +%F)"
