name: Docker Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing the build
      - run: docker build -t muhhassani/pyiron-precice:latest .
      - run: docker tag muhhassani/pyiron-precice:latest muhhassani/pyiron-precice:"$(date +%F)"
